Repository AY2122S2-CS2103T-T09-4/tp, pull requests merged in 2022-03, with the labels that each got.

#8 Update UserGuide
  docs/UserGuide.md
Labels: documentation

#15 Update Project Website (Xin Wei)
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/redpelican2108.png.jpg
  docs/team/redpelican2108.md
Labels: documentation

#17 Update Project Website (Tan Kel Zin)
  docs/AboutUs.md
  docs/images/mechfrog88.png
  docs/team/mechfrog88.md
Labels: documentation

#20 Update project website (README.md and _config.yml)
  README.md
  docs/_config.yml
  docs/images/redpelican2108.png
Labels: documentation

#24 Update readme UI.png
  docs/images/Ui.png
Labels: documentation

#41 Modify list command
  src/main/java/seedu/ibook/logic/commands/AddCommand.java
  src/main/java/seedu/ibook/logic/commands/FindCommand.java
  src/main/java/seedu/ibook/logic/commands/ListCommand.java
  src/main/java/seedu/ibook/logic/commands/UpdateCommand.java
  src/main/java/seedu/ibook/logic/parser/FindCommandParser.java
  src/main/java/seedu/ibook/logic/parser/IBookParser.java
  src/main/java/seedu/ibook/model/Model.java
  src/main/java/seedu/ibook/model/ModelManager.java
  src/main/java/seedu/ibook/model/product/Category.java
  src/main/java/seedu/ibook/model/product/Description.java
  src/main/java/seedu/ibook/model/product/ExpiryDate.java
  src/main/java/seedu/ibook/model/product/Name.java
  src/main/java/seedu/ibook/model/product/NameContainsKeywordsPredicate.java
  src/main/java/seedu/ibook/model/product/Price.java
  src/main/java/seedu/ibook/model/product/Product.java
  src/main/java/seedu/ibook/model/product/ProductFulfillsFiltersPredicate.java
  src/test/java/seedu/ibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ibook/logic/commands/FindCommandTest.java
  src/test/java/seedu/ibook/logic/commands/ListCommandTest.java
  src/test/java/seedu/ibook/logic/parser/FindCommandParserTest.java
Labels: type.Task

#46 Improve UI and Implements Button
  src/main/java/seedu/ibook/ui/CommandBox.java
  src/main/java/seedu/ibook/ui/MainWindow.java
  src/main/java/seedu/ibook/ui/MenuToolbar.java
  src/main/java/seedu/ibook/ui/ProductCard.java
  src/main/java/seedu/ibook/ui/ResultWindow.java
  src/main/java/seedu/ibook/ui/Table.java
  src/main/java/seedu/ibook/ui/TableContent.java
  src/main/java/seedu/ibook/ui/TableHeader.java
  src/main/java/seedu/ibook/ui/UiManager.java
  src/main/java/seedu/ibook/ui/UiPart.java
  src/main/java/seedu/ibook/ui/popup/Popup.java
  src/main/java/seedu/ibook/ui/popup/PopupAdd.java
  src/main/java/seedu/ibook/ui/popup/PopupDelete.java
  src/main/java/seedu/ibook/ui/popup/PopupUpdate.java
  src/main/java/seedu/ibook/ui/table/ProductCard.java
  src/main/java/seedu/ibook/ui/table/Table.java
  src/main/java/seedu/ibook/ui/table/TableContent.java
  src/main/java/seedu/ibook/ui/table/TableHeader.java
  src/main/resources/images/edit-color.png
  src/main/resources/images/edit.png
  src/main/resources/images/trash-2-color.png
  src/main/resources/images/trash-2.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MenuToolbar.fxml
  src/main/resources/view/ProductCard.fxml
  src/main/resources/view/ResultWindow.fxml
  src/main/resources/view/Table.fxml
  src/main/resources/view/Table/ProductCard.fxml
  src/main/resources/view/Table/Table.fxml
  src/main/resources/view/Table/TableContent.fxml
  src/main/resources/view/Table/TableHeader.fxml
  src/main/resources/view/TableContent.fxml
  src/main/resources/view/TableHeader.fxml
  src/main/resources/view/css/commandBox.css
  src/main/resources/view/css/global.css
  src/main/resources/view/css/menuToolbar.css
  src/main/resources/view/css/popup.css
  src/main/resources/view/css/resultWindow.css
  src/main/resources/view/css/table.css
  src/main/resources/view/font/NotoSans-Regular.ttf
  src/main/resources/view/font/NotoSans-Thin.ttf
  src/main/resources/view/global.css
  src/main/resources/view/popup/PopupAdd.fxml
  src/main/resources/view/popup/PopupDelete.fxml
  src/main/resources/view/popup/PopupUpdate.fxml
Labels: enhancement

#68 [!Merge this before updating userguide] Update userguide
  docs/UserGuide.md
Labels: documentation

#71 Improve Class Structure of UI
  src/main/java/seedu/ibook/ui/CommandBox.java
  src/main/java/seedu/ibook/ui/MainWindow.java
  src/main/java/seedu/ibook/ui/MenuToolbar.java
  src/main/java/seedu/ibook/ui/ResultWindow.java
  src/main/java/seedu/ibook/ui/UiComponent.java
  src/main/java/seedu/ibook/ui/popup/Popup.java
  src/main/java/seedu/ibook/ui/popup/PopupAdd.java
  src/main/java/seedu/ibook/ui/popup/PopupDelete.java
  src/main/java/seedu/ibook/ui/popup/PopupHandler.java
  src/main/java/seedu/ibook/ui/popup/PopupUpdate.java
  src/main/java/seedu/ibook/ui/table/ProductCard.java
  src/main/java/seedu/ibook/ui/table/Table.java
  src/main/java/seedu/ibook/ui/table/TableContent.java
  src/main/java/seedu/ibook/ui/table/TableHeader.java
  src/main/resources/view/css/global.css
  src/main/resources/view/popup/PopupAdd.fxml
  src/main/resources/view/popup/PopupDelete.fxml
  src/main/resources/view/popup/PopupUpdate.fxml
Labels: priority.Low

#72 Update documentations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation

#75 Update UI DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiPopupDiagram.puml
  docs/diagrams/UiTableDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/UiPopupDiagram.png
  docs/images/UiTableDiagram.png
Labels: documentation

#73 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: documentation

#78 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation, priority.High

#81 Update Documentation for v1.2
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiPopupDiagram.puml
  docs/diagrams/UiTableDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/style.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/UiPopupDiagram.png
  docs/images/UiTableDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation

#44 Add item object
  src/main/java/seedu/ibook/logic/commands/UpdateCommand.java
  src/main/java/seedu/ibook/logic/parser/AddCommandParser.java
  src/main/java/seedu/ibook/logic/parser/FindCommandParser.java
  src/main/java/seedu/ibook/logic/parser/ParserUtil.java
  src/main/java/seedu/ibook/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/ibook/model/item/ExpiryDate.java
  src/main/java/seedu/ibook/model/item/Item.java
  src/main/java/seedu/ibook/model/item/Quantity.java
  src/main/java/seedu/ibook/model/item/UniqueItemList.java
  src/main/java/seedu/ibook/model/item/exceptions/ItemNotFoundException.java
  src/main/java/seedu/ibook/model/product/Product.java
  src/main/java/seedu/ibook/model/util/SampleDataUtil.java
  src/main/java/seedu/ibook/storage/JsonAdaptedItem.java
  src/main/java/seedu/ibook/storage/JsonAdaptedProduct.java
  src/main/java/seedu/ibook/ui/popup/PopupUpdate.java
  src/main/java/seedu/ibook/ui/table/ProductCard.java
  src/test/data/JsonIBookStorageTest/invalidProductIBook.json
  src/test/data/JsonSerializableIBookTest/duplicateProductIBook.json
  src/test/data/JsonSerializableIBookTest/invalidProductIBook.json
  src/test/data/JsonSerializableIBookTest/typicalProductsIBook.json
  src/test/java/seedu/ibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ibook/logic/commands/FindCommandTest.java
  src/test/java/seedu/ibook/logic/commands/UpdateProductDescriptorTest.java
  src/test/java/seedu/ibook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ibook/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/ibook/model/item/ItemTest.java
  src/test/java/seedu/ibook/model/item/UniqueItemListTest.java
  src/test/java/seedu/ibook/storage/JsonAdaptedProductTest.java
  src/test/java/seedu/ibook/testutil/ItemBuilder.java
  src/test/java/seedu/ibook/testutil/ProductBuilder.java
  src/test/java/seedu/ibook/testutil/ProductUtil.java
  src/test/java/seedu/ibook/testutil/TypicalItems.java
  src/test/java/seedu/ibook/testutil/TypicalProducts.java
  src/test/java/seedu/ibook/testutil/UpdateProductDescriptorBuilder.java
Labels: severity.High

#97 Update UI for Items
  src/main/java/seedu/ibook/model/product/Product.java
  src/main/java/seedu/ibook/ui/MainWindow.java
  src/main/java/seedu/ibook/ui/popup/PopupAdd.java
  src/main/java/seedu/ibook/ui/table/ProductCard.java
  src/main/java/seedu/ibook/ui/table/ProductTable.java
  src/main/java/seedu/ibook/ui/table/Table.java
  src/main/java/seedu/ibook/ui/table/TableHeader.java
  src/main/java/seedu/ibook/ui/table/item/ItemCard.java
  src/main/java/seedu/ibook/ui/table/item/ItemTable.java
  src/main/resources/images/chevron-right.png
  src/main/resources/images/file-plus.png
  src/main/resources/view/Table/Item/ItemCard.fxml
  src/main/resources/view/Table/Item/ItemTable.fxml
  src/main/resources/view/Table/ProductCard.fxml
  src/main/resources/view/Table/ProductTable.fxml
  src/main/resources/view/Table/Table.fxml
  src/main/resources/view/Table/TableContent.fxml
  src/main/resources/view/Table/TableHeader.fxml
  src/main/resources/view/css/ItemTable.css
  src/main/resources/view/css/global.css
  src/main/resources/view/css/resultWindow.css
  src/main/resources/view/css/table.css
  src/main/resources/view/font/NotoSans-SemiBold.ttf
  src/main/resources/view/popup/PopupAdd.fxml
  src/main/resources/view/popup/PopupUpdate.fxml
Labels: enhancement, type.Enhancement, priority.High

#105 Implement display filters in UI
  src/main/java/seedu/ibook/logic/Logic.java
  src/main/java/seedu/ibook/logic/LogicManager.java
  src/main/java/seedu/ibook/logic/commands/FindCommand.java
  src/main/java/seedu/ibook/logic/commands/ListCommand.java
  src/main/java/seedu/ibook/logic/commands/UpdateCommand.java
  src/main/java/seedu/ibook/logic/parser/FindCommandParser.java
  src/main/java/seedu/ibook/model/Model.java
  src/main/java/seedu/ibook/model/ModelManager.java
  src/main/java/seedu/ibook/model/product/Category.java
  src/main/java/seedu/ibook/model/product/Description.java
  src/main/java/seedu/ibook/model/product/Name.java
  src/main/java/seedu/ibook/model/product/Price.java
  src/main/java/seedu/ibook/model/product/ProductFulfillsFiltersPredicate.java
  src/main/java/seedu/ibook/model/product/exceptions/FilterNotFoundException.java
  src/main/java/seedu/ibook/model/product/filters/AttributeFilter.java
  src/main/java/seedu/ibook/model/product/filters/CategoryFilter.java
  src/main/java/seedu/ibook/model/product/filters/DescriptionFilter.java
  src/main/java/seedu/ibook/model/product/filters/NameFilter.java
  src/main/java/seedu/ibook/model/product/filters/PriceFilter.java
  src/main/java/seedu/ibook/model/product/filters/ProductFulfillsFiltersPredicate.java
  src/main/java/seedu/ibook/ui/MainWindow.java
  src/main/java/seedu/ibook/ui/filters/FilterButton.java
  src/main/java/seedu/ibook/ui/filters/FilterList.java
  src/main/java/seedu/ibook/ui/table/ProductTable.java
  src/main/resources/view/Filters/FilterButton.fxml
  src/main/resources/view/Filters/FilterList.fxml
  src/test/java/seedu/ibook/logic/commands/AddCommandTest.java
  src/test/java/seedu/ibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ibook/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/ibook/logic/commands/FindCommandTest.java
  src/test/java/seedu/ibook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/IBookParserTest.java
  src/test/java/seedu/ibook/model/ModelManagerTest.java
  src/test/java/seedu/ibook/testutil/ProductBuilder.java
Labels: severity.Medium

#101 Create AddItemCommand
  src/main/java/seedu/ibook/commons/core/Distinguishable.java
  src/main/java/seedu/ibook/commons/core/UniqueList.java
  src/main/java/seedu/ibook/commons/core/exceptions/DuplicateElementException.java
  src/main/java/seedu/ibook/commons/core/exceptions/ElementNotFoundException.java
  src/main/java/seedu/ibook/commons/util/StringUtil.java
  src/main/java/seedu/ibook/logic/commands/AddCommand.java
  src/main/java/seedu/ibook/logic/commands/AddItemCommand.java
  src/main/java/seedu/ibook/logic/commands/UpdateCommand.java
  src/main/java/seedu/ibook/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/ibook/logic/parser/CliSyntax.java
  src/main/java/seedu/ibook/logic/parser/FindCommandParser.java
  src/main/java/seedu/ibook/logic/parser/IBookParser.java
  src/main/java/seedu/ibook/logic/parser/ParserUtil.java
  src/main/java/seedu/ibook/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/ibook/model/IBook.java
  src/main/java/seedu/ibook/model/Model.java
  src/main/java/seedu/ibook/model/ModelManager.java
  src/main/java/seedu/ibook/model/item/Item.java
  src/main/java/seedu/ibook/model/item/Quantity.java
  src/main/java/seedu/ibook/model/item/UniqueItemList.java
  src/main/java/seedu/ibook/model/item/exceptions/ItemNotFoundException.java
  src/main/java/seedu/ibook/model/product/Product.java
  src/main/java/seedu/ibook/model/product/UniqueProductList.java
  src/main/java/seedu/ibook/model/product/exceptions/DuplicateProductException.java
  src/main/java/seedu/ibook/model/product/exceptions/ProductNotFoundException.java
  src/main/java/seedu/ibook/storage/JsonAdaptedItem.java
  src/main/java/seedu/ibook/storage/JsonAdaptedProduct.java
  src/test/java/seedu/ibook/logic/commands/AddCommandTest.java
  src/test/java/seedu/ibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ibook/logic/parser/AddItemCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/ibook/model/IBookTest.java
  src/test/java/seedu/ibook/model/item/ItemTest.java
  src/test/java/seedu/ibook/model/item/UniqueItemListTest.java
  src/test/java/seedu/ibook/testutil/ItemBuilder.java
  src/test/java/seedu/ibook/testutil/TypicalItems.java
Labels: priority.High

#112 Create DeleteItemCommand
  src/main/java/seedu/ibook/commons/core/Messages.java
  src/main/java/seedu/ibook/commons/core/index/CompoundIndex.java
  src/main/java/seedu/ibook/commons/util/StringUtil.java
  src/main/java/seedu/ibook/logic/commands/DeleteCommand.java
  src/main/java/seedu/ibook/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/ibook/logic/parser/DeleteItemCommandParser.java
  src/main/java/seedu/ibook/logic/parser/IBookParser.java
  src/main/java/seedu/ibook/logic/parser/ParserUtil.java
  src/main/java/seedu/ibook/model/IBook.java
  src/main/java/seedu/ibook/model/Model.java
  src/main/java/seedu/ibook/model/ModelManager.java
  src/main/java/seedu/ibook/model/item/Item.java
  src/main/java/seedu/ibook/storage/JsonAdaptedProduct.java
  src/test/java/seedu/ibook/logic/commands/AddCommandTest.java
Labels: priority.Medium

#115 Update documentation
  docs/DeveloperGuide.md
  docs/diagrams/DetailedModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/DetailedModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  src/main/java/seedu/ibook/model/product/Price.java
Labels: documentation

#119 Add tests, fix bugs
  src/main/java/seedu/ibook/commons/core/UniqueList.java
  src/main/java/seedu/ibook/logic/commands/ExpiredCommand.java
  src/main/java/seedu/ibook/logic/commands/FindCommand.java
  src/main/java/seedu/ibook/logic/commands/ListCommand.java
  src/main/java/seedu/ibook/logic/commands/UpdateCommand.java
  src/main/java/seedu/ibook/logic/parser/FindCommandParser.java
  src/main/java/seedu/ibook/logic/parser/IBookParser.java
  src/main/java/seedu/ibook/model/Model.java
  src/main/java/seedu/ibook/model/ModelManager.java
  src/main/java/seedu/ibook/model/product/Description.java
  src/main/java/seedu/ibook/model/product/filters/ExpiredFilter.java
  src/main/java/seedu/ibook/model/product/filters/ProductFilter.java
  src/test/java/seedu/ibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ibook/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/ibook/logic/commands/FindCommandTest.java
  src/test/java/seedu/ibook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/IBookParserTest.java
  src/test/java/seedu/ibook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ibook/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/ibook/model/ModelManagerTest.java
  src/test/java/seedu/ibook/model/product/ProductTest.java
  src/test/java/seedu/ibook/model/product/filters/ProductFilterTest.java
  src/test/java/seedu/ibook/storage/JsonAdaptedProductTest.java
  src/test/java/seedu/ibook/testutil/TypicalProductFilters.java
  src/test/java/seedu/ibook/testutil/TypicalProducts.java
Labels: enhancement

#131 Add table empty state
  docs/DeveloperGuide.md
  src/main/java/seedu/ibook/ui/table/EmptyProductTableState.java
  src/main/java/seedu/ibook/ui/table/ProductTable.java
  src/main/java/seedu/ibook/ui/table/item/EmptyItemTableState.java
  src/main/java/seedu/ibook/ui/table/item/ItemTable.java
  src/main/resources/images/empty-item.png
  src/main/resources/images/empty-product.png
  src/main/resources/view/Table/EmptyProductTableState.fxml
  src/main/resources/view/Table/Item/EmptyItemTableState.fxml
  src/main/resources/view/css/emptyTable.css
  src/main/resources/view/css/global.css
  src/main/resources/view/css/table.css
  src/main/resources/view/font/MonoLisa-Regular.otf
Labels: enhancement

#128 Improve Find Command
  src/main/java/seedu/ibook/logic/commands/FindCommand.java
  src/main/java/seedu/ibook/logic/parser/CliSyntax.java
  src/main/java/seedu/ibook/logic/parser/FindCommandParser.java
  src/main/java/seedu/ibook/model/product/Category.java
  src/main/java/seedu/ibook/model/product/Description.java
  src/main/java/seedu/ibook/model/product/Name.java
  src/main/java/seedu/ibook/model/product/Price.java
  src/main/java/seedu/ibook/model/product/filters/CategoryFilter.java
  src/main/java/seedu/ibook/model/product/filters/DescriptionFilter.java
  src/main/java/seedu/ibook/model/product/filters/NameFilter.java
  src/main/java/seedu/ibook/model/product/filters/PriceFilter.java
  src/test/java/seedu/ibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ibook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/ibook/model/product/filters/CategoryFilterTest.java
  src/test/java/seedu/ibook/model/product/filters/DescriptionFilterTest.java
  src/test/java/seedu/ibook/model/product/filters/NameFilterTest.java
  src/test/java/seedu/ibook/model/product/filters/PriceFilterTest.java
  src/test/java/seedu/ibook/testutil/TypicalProductFilters.java
Labels: enhancement

#108 Implement undo-redo feature
  src/main/java/seedu/ibook/logic/commands/AddCommand.java
  src/main/java/seedu/ibook/logic/commands/AddItemCommand.java
  src/main/java/seedu/ibook/logic/commands/ClearCommand.java
  src/main/java/seedu/ibook/logic/commands/DeleteAllCommand.java
  src/main/java/seedu/ibook/logic/commands/DeleteCommand.java
  src/main/java/seedu/ibook/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/ibook/logic/commands/RedoCommand.java
  src/main/java/seedu/ibook/logic/commands/UndoCommand.java
  src/main/java/seedu/ibook/logic/commands/UpdateAllCommand.java
  src/main/java/seedu/ibook/logic/commands/UpdateCommand.java
  src/main/java/seedu/ibook/logic/commands/UpdateItemCommand.java
  src/main/java/seedu/ibook/logic/parser/IBookParser.java
  src/main/java/seedu/ibook/model/IBook.java
  src/main/java/seedu/ibook/model/Model.java
  src/main/java/seedu/ibook/model/ModelManager.java
  src/main/java/seedu/ibook/model/ReadOnlyIBook.java
  src/main/java/seedu/ibook/model/ReversibleIBook.java
  src/main/java/seedu/ibook/model/StateChangeRecorder.java
  src/main/java/seedu/ibook/model/actions/ReversibleAddItemAction.java
  src/main/java/seedu/ibook/model/actions/ReversibleAddProductAction.java
  src/main/java/seedu/ibook/model/actions/ReversibleIBookAction.java
  src/main/java/seedu/ibook/model/actions/ReversibleRemoveItemAction.java
  src/main/java/seedu/ibook/model/actions/ReversibleRemoveProductAction.java
  src/main/java/seedu/ibook/model/actions/ReversibleResetDataAction.java
  src/main/java/seedu/ibook/model/actions/ReversibleSetItemAction.java
  src/main/java/seedu/ibook/model/actions/ReversibleSetProductAction.java
  src/main/java/seedu/ibook/model/exceptions/AtLatestStateException.java
  src/main/java/seedu/ibook/model/exceptions/AtOldestStateException.java
  src/test/java/seedu/ibook/logic/commands/AddCommandTest.java
  src/test/java/seedu/ibook/logic/commands/ClearCommandTest.java
  src/test/java/seedu/ibook/logic/commands/RedoCommandTest.java
  src/test/java/seedu/ibook/logic/commands/UndoCommandTest.java
  src/test/java/seedu/ibook/logic/parser/IBookParserTest.java
  src/test/java/seedu/ibook/model/IBookTest.java
  src/test/java/seedu/ibook/model/ReversibleIBookActionsTest.java
  src/test/java/seedu/ibook/model/ReversibleIBookTest.java
  src/test/java/seedu/ibook/model/StateChangeRecorderTest.java
  src/test/java/seedu/ibook/testutil/TypicalReversibleIBookActions.java
Labels: enhancement

#135 Discount Feature and Item-Product Navigability
  src/main/java/seedu/ibook/logic/commands/AddCommand.java
  src/main/java/seedu/ibook/logic/commands/AddItemCommand.java
  src/main/java/seedu/ibook/logic/commands/UpdateCommand.java
  src/main/java/seedu/ibook/logic/commands/UpdateItemCommand.java
  src/main/java/seedu/ibook/logic/parser/AddCommandParser.java
  src/main/java/seedu/ibook/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/ibook/logic/parser/CliSyntax.java
  src/main/java/seedu/ibook/logic/parser/ParserUtil.java
  src/main/java/seedu/ibook/logic/parser/UpdateAllCommandParser.java
  src/main/java/seedu/ibook/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/ibook/model/IBook.java
  src/main/java/seedu/ibook/model/item/ExpiryDate.java
  src/main/java/seedu/ibook/model/item/Item.java
  src/main/java/seedu/ibook/model/item/ItemDescriptor.java
  src/main/java/seedu/ibook/model/item/UniqueItemList.java
  src/main/java/seedu/ibook/model/product/Category.java
  src/main/java/seedu/ibook/model/product/Description.java
  src/main/java/seedu/ibook/model/product/DiscountRate.java
  src/main/java/seedu/ibook/model/product/DiscountStart.java
  src/main/java/seedu/ibook/model/product/Name.java
  src/main/java/seedu/ibook/model/product/Price.java
  src/main/java/seedu/ibook/model/product/Product.java
  src/main/java/seedu/ibook/model/util/SampleDataUtil.java
  src/main/java/seedu/ibook/storage/JsonAdaptedItem.java
  src/main/java/seedu/ibook/storage/JsonAdaptedProduct.java
  src/main/java/seedu/ibook/ui/CommandBox.java
  src/main/java/seedu/ibook/ui/popup/PopupAddProduct.java
  src/main/java/seedu/ibook/ui/popup/PopupUpdateProduct.java
  src/main/java/seedu/ibook/ui/table/ProductCard.java
  src/main/java/seedu/ibook/ui/table/item/ItemCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultWindow.fxml
  src/main/resources/view/popup/PopupAddProduct.fxml
  src/main/resources/view/popup/PopupUpdateProduct.fxml
  src/main/resources/view/table/ProductCard.fxml
  src/main/resources/view/table/ProductTable.fxml
  src/main/resources/view/table/item/ItemCard.fxml
  src/main/resources/view/table/item/ItemTable.fxml
  src/test/data/JsonIBookStorageTest/invalidAndValidProductIBook.json
  src/test/data/JsonIBookStorageTest/invalidProductIBook.json
  src/test/data/JsonSerializableIBookTest/duplicateProductIBook.json
  src/test/data/JsonSerializableIBookTest/invalidProductIBook.json
  src/test/data/JsonSerializableIBookTest/typicalProductsIBook.json
  src/test/java/seedu/ibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ibook/logic/commands/ExpiredCommandTest.java
  src/test/java/seedu/ibook/logic/commands/OutOfStockCommandTest.java
  src/test/java/seedu/ibook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/AddItemCommandParserTest.java
  src/test/java/seedu/ibook/model/item/ItemTest.java
  src/test/java/seedu/ibook/model/item/UniqueItemListTest.java
  src/test/java/seedu/ibook/model/product/ProductTest.java
  src/test/java/seedu/ibook/storage/JsonAdaptedProductTest.java
  src/test/java/seedu/ibook/testutil/ItemBuilder.java
  src/test/java/seedu/ibook/testutil/ProductBuilder.java
  src/test/java/seedu/ibook/testutil/ProductUtil.java
  src/test/java/seedu/ibook/testutil/TypicalItems.java
  src/test/java/seedu/ibook/testutil/TypicalProducts.java
  src/test/java/seedu/ibook/testutil/UpdateProductDescriptorBuilder.java
Labels: enhancement

#149 Fix bugs
  src/main/java/seedu/ibook/model/item/ExpiryDate.java
  src/main/java/seedu/ibook/model/product/DiscountRate.java
  src/main/java/seedu/ibook/model/product/DiscountStart.java
  src/main/java/seedu/ibook/ui/MainWindow.java
  src/main/java/seedu/ibook/ui/popup/PopupHandler.java
  src/main/java/seedu/ibook/ui/table/item/ItemTable.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/popup/PopupAddProduct.fxml
Labels: type.Bug

#160 Update documentation
  docs/UserGuide.md
  docs/images/ui-icons/add-icon.png
  docs/images/ui-icons/add-product.png
  docs/images/ui-icons/chevron-right.png
  docs/images/ui-icons/edit-color.png
  docs/images/ui-icons/edit.png
  docs/images/ui-icons/empty-item.png
  docs/images/ui-icons/empty-product.png
  docs/images/ui-icons/file-plus-color.png
  docs/images/ui-icons/file-plus.png
  docs/images/ui-icons/help.png
  docs/images/ui-icons/iBook.png
  docs/images/ui-icons/plus-circle.png
  docs/images/ui-icons/terminal.png
  docs/images/ui-icons/trash-2-color.png
  docs/images/ui-icons/trash-2.png
  docs/images/ui-icons/x.png
Labels: documentation

#155 Allow special characters in attribute
  src/main/java/seedu/ibook/logic/parser/AddCommandParser.java
  src/main/java/seedu/ibook/logic/parser/ParserUtil.java
  src/main/java/seedu/ibook/model/product/Category.java
  src/main/java/seedu/ibook/model/product/Description.java
  src/main/java/seedu/ibook/model/product/DiscountStart.java
  src/main/java/seedu/ibook/model/product/Name.java
  src/test/java/seedu/ibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ibook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ibook/logic/parser/UpdateAllCommandParserTest.java
  src/test/java/seedu/ibook/logic/parser/UpdateCommandParserTest.java
Labels: type.Bug

#159 Fix bugs
  src/main/java/seedu/ibook/ui/HelpWindow.java
  src/main/java/seedu/ibook/ui/table/ProductCard.java
  src/main/java/seedu/ibook/ui/table/item/ItemTable.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug

#168 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/ui-icons/filter-tag.png
  src/main/resources/images/copy.png
Labels: documentation
