Repository AY2122S2-CS2103T-T09-4/tp, pull requests merged in 2022-04, with the labels that each got.

#220 Fix bugs
  src/main/java/seedu/ibook/commons/core/GuiSettings.java
  src/main/java/seedu/ibook/logic/commands/item/AddItemCommand.java
  src/main/java/seedu/ibook/logic/commands/item/DeleteItemCommand.java
  src/main/java/seedu/ibook/logic/commands/item/UpdateItemCommand.java
  src/main/java/seedu/ibook/model/ModelManager.java
  src/main/java/seedu/ibook/model/item/FilteredItemList.java
  src/main/java/seedu/ibook/model/product/Product.java
  src/main/java/seedu/ibook/ui/MainWindow.java
  src/main/java/seedu/ibook/ui/control/Filter.java
  src/main/java/seedu/ibook/ui/table/ProductCard.java
  src/main/java/seedu/ibook/ui/table/item/ItemTable.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/popup/PopupUpdateProduct.fxml
  src/main/resources/view/table/ProductCard.fxml
  src/main/resources/view/table/ProductTable.fxml
  src/test/java/seedu/ibook/logic/commands/product/ExpiredCommandTest.java
  src/test/java/seedu/ibook/logic/commands/product/OutOfStockCommandTest.java
Labels: type.Bug

#224 Fix user guide bugs
  docs/UserGuide.md
Labels: type.Bug, documentation

#222 Fix bugs and add tests
  src/main/java/seedu/ibook/logic/commands/item/AddItemCommand.java
  src/main/java/seedu/ibook/logic/commands/item/UpdateItemCommand.java
  src/main/java/seedu/ibook/model/actions/ReversibleAddItemAction.java
  src/main/java/seedu/ibook/model/actions/ReversibleSetItemAction.java
  src/main/java/seedu/ibook/model/item/ExpiryDate.java
  src/main/java/seedu/ibook/model/item/Item.java
  src/main/java/seedu/ibook/model/item/ItemDescriptor.java
  src/main/java/seedu/ibook/model/item/Quantity.java
  src/main/java/seedu/ibook/model/product/Product.java
  src/test/java/seedu/ibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/ibook/logic/commands/item/UpdateItemCommandTest.java
  src/test/java/seedu/ibook/logic/commands/item/UpdateItemDescriptorTest.java
  src/test/java/seedu/ibook/logic/commands/product/UpdateAllCommandTest.java
  src/test/java/seedu/ibook/logic/commands/product/UpdateCommandTest.java
  src/test/java/seedu/ibook/logic/commands/product/UpdateProductDescriptorTest.java
  src/test/java/seedu/ibook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/ibook/logic/parser/UpdateItemCommandParserTest.java
  src/test/java/seedu/ibook/testutil/UpdateItemDescriptorBuilder.java
Labels: type.Bug

#226 Fix bugs
  src/main/java/seedu/ibook/model/ModelManager.java
  src/main/java/seedu/ibook/ui/CommandBox.java
  src/main/java/seedu/ibook/ui/MainWindow.java
  src/main/java/seedu/ibook/ui/popup/Popup.java
  src/main/java/seedu/ibook/ui/table/ProductCard.java
Labels: type.Bug

#219 Update UG to cover certain usages
  docs/UserGuide.md
Labels: documentation

#232 Fix bugs
  src/main/java/seedu/ibook/MainApp.java
  src/main/java/seedu/ibook/model/item/Quantity.java
  src/main/java/seedu/ibook/model/product/Category.java
  src/main/java/seedu/ibook/model/product/DiscountRate.java
  src/main/java/seedu/ibook/model/product/DiscountStart.java
  src/main/java/seedu/ibook/model/product/Name.java
  src/main/java/seedu/ibook/model/product/Price.java
  src/main/java/seedu/ibook/model/product/PriceRange.java
  src/main/java/seedu/ibook/ui/popup/PopupAddProduct.java
  src/main/java/seedu/ibook/ui/popup/PopupDeleteProduct.java
  src/main/java/seedu/ibook/ui/popup/PopupUpdateProduct.java
  src/main/java/seedu/ibook/ui/popup/item/PopupAddItem.java
  src/main/java/seedu/ibook/ui/popup/item/PopupManageItem.java
  src/test/java/seedu/ibook/logic/commands/ExitCommandTest.java
  src/test/java/seedu/ibook/logic/commands/HelpCommandTest.java
Labels: type.Bug

#239 Update User Guide
  docs/UserGuide.md
Labels: documentation

#241 Fix table of content not showing
  docs/UserGuide.md
Labels: documentation

#242 Fix table of content not showing
  docs/UserGuide.md
Labels: documentation

#245 Update Project Portfolio Page
  docs/team/davidtan0527.md
Labels: documentation

#246 Update Project Portfolio Page
  docs/team/1001mei.md
Labels: documentation

#247 Update PPP
  docs/team/redpelican2108.md
Labels: documentation

#244 Update mechfrog88's PPP
  docs/team/mechfrog88.md
Labels: documentation

#254 Fix empty category issue
  docs/UserGuide.md
  src/main/java/seedu/ibook/model/product/Category.java
Labels: type.Bug, documentation

#253 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DetailedModelClassDiagram.puml
  docs/diagrams/FindCreationSequenceDiagram.puml
  docs/diagrams/FindExecutionSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ProductFilterClassDiagram.puml
  docs/images/DetailedModelClassDiagram.png
  docs/images/FindCreationSequenceDiagram.png
  docs/images/FindExecutionSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ProductFilterClassDiagram.png
  src/main/java/seedu/ibook/commons/core/Messages.java
  src/main/java/seedu/ibook/logic/commands/item/ExpiredCommand.java
  src/main/java/seedu/ibook/logic/commands/item/RemindCommand.java
  src/main/java/seedu/ibook/logic/commands/product/FindCommand.java
  src/main/java/seedu/ibook/logic/commands/product/OutOfStockCommand.java
  src/main/java/seedu/ibook/logic/parser/IBookParser.java
  src/main/java/seedu/ibook/logic/parser/RemindCommandParser.java
  src/main/java/seedu/ibook/ui/MenuToolbar.java
  src/main/resources/view/MenuToolbar.fxml
  src/test/java/seedu/ibook/logic/commands/FindCommandTest.java
  src/test/java/seedu/ibook/logic/commands/product/ExpiredCommandTest.java
  src/test/java/seedu/ibook/logic/commands/product/OutOfStockCommandTest.java
  src/test/java/seedu/ibook/logic/commands/product/RemindCommandTest.java
  src/test/java/seedu/ibook/logic/parser/IBookParserTest.java
  src/test/java/seedu/ibook/logic/parser/RemindCommandParserTest.java
Labels: documentation

#256 Improve User Guide
  docs/UserGuide.md
  docs/images/Ui-2.png
  docs/images/popup-add-item.png
  docs/images/popup-add-product.png
  docs/images/popup-delete-product.png
  docs/images/popup-modify-item.png
  docs/images/popup-update-product.png
Labels: documentation

#258 Update PPP
  docs/team/mazx4960.md
Labels: documentation

#261 Update DG for Ui
  docs/DeveloperGuide.md
  docs/diagrams/ExecutePopupSequenceDiagram.puml
  docs/diagrams/ShowPopupSequenceDiagram.puml
  docs/diagrams/Style.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiControlDiagram.puml
  docs/diagrams/UiPopupDiagram.puml
  docs/diagrams/UiTableDiagram.puml
  docs/images/ExecutePopupSequenceDiagram.png
  docs/images/ShowPopupSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiControlDiagram.png
  docs/images/UiPopupDiagram.png
  docs/images/UiTableDiagram.png
  src/main/java/seedu/ibook/ui/control/ControlBox.java
  src/main/java/seedu/ibook/ui/table/ProductTable.java
  src/main/java/seedu/ibook/ui/table/item/ItemTable.java
  src/main/resources/view/control/ControlBox.fxml
Labels: documentation

#266 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddItemSequenceDiagram.puml
  docs/diagrams/AddItemToUniqueItemList.puml
  docs/images/AddItemSequenceDiagram.png
  docs/images/AddItemToUniqueItemList.png
  docs/team/mazx4960.md
Labels: documentation

#270 Refactor UserGuide
  docs/UserGuide.md
  docs/images/item-card.png
  docs/images/product-card.png
  docs/images/product-table.png
  docs/images/ui-icons/add-item-icon.png
Labels: documentation

#272 UG cleanup
  docs/UserGuide.md
Labels: documentation

#273 Fix colon that is not escaped will result in wrong error issue
  docs/UserGuide.md
  src/main/java/seedu/ibook/commons/util/StringUtil.java
  src/main/java/seedu/ibook/ui/popup/Popup.java
  src/main/java/seedu/ibook/ui/popup/PopupAddProduct.java
  src/main/java/seedu/ibook/ui/popup/PopupUpdateProduct.java
  src/main/java/seedu/ibook/ui/popup/item/PopupAddItem.java
  src/main/java/seedu/ibook/ui/popup/item/PopupManageItem.java
Labels: type.Bug

#275 Update PPP
  docs/team/mechfrog88.md
Labels: documentation

#277 Fix grammar issue
  docs/DeveloperGuide.md
Labels: documentation

#278 Add page breaks for DG
  docs/DeveloperGuide.md
Labels: documentation
